<ns0:svg xmlns:ns0="http://www.w3.org/2000/svg" xmlns:ns1="http://www.w3.org/1999/xlink" width="0pt" height="864pt" viewBox="0.00 0.00 0.22 864.00">
<ns0:g id="graph0" class="graph" transform="scale(0.000576741 0.000576741) rotate(0) translate(4 1498067.6)">
<ns0:title>inheritance193ec17ad4</ns0:title>

<ns0:g id="node1" class="node">
<ns0:title>InternalErrorOccurred</ns0:title>
<ns0:g id="a_node1"><ns0:a ns1:href="../pyEDAA.UCIS/pyEDAA.UCIS.UCDB.html#pyEDAA.UCIS.UCDB.InternalErrorOccurred" ns1:title="Raised when internal error occurred" target="_top">
<ns0:polygon fill="white" stroke="black" stroke-width="0.5" points="368,-749041.05 194.5,-749041.05 194.5,-749022.55 368,-749022.55 368,-749041.05" />
<ns0:text text-anchor="middle" x="281.25" y="-749027.55" font-family="Vera Sans, DejaVu Sans, Liberation Sans, Arial, Helvetica, sans" font-size="10.00">InternalErrorOccurred</ns0:text>
</ns0:a>
</ns0:g>
</ns0:g>

<ns0:g id="node2" class="node">
<ns0:title>UcdbParserException</ns0:title>
<ns0:g id="a_node2"><ns0:a ns1:href="../pyEDAA.UCIS/pyEDAA.UCIS.UCDB.html#pyEDAA.UCIS.UCDB.UcdbParserException" ns1:title="Base-class for other UCDB Parser exceptions" target="_top">
<ns0:polygon fill="white" stroke="black" stroke-width="0.5" points="158.5,-1498063.6 0,-1498063.6 0,0 158.5,0 158.5,-1498063.6" />
<ns0:text text-anchor="middle" x="79.25" y="-1498050.1" font-family="Vera Sans, DejaVu Sans, Liberation Sans, Arial, Helvetica, sans" font-size="10.00">UcdbParserException</ns0:text>
</ns0:a>
</ns0:g>
</ns0:g>

<ns0:g id="edge1" class="edge">
<ns0:title>UcdbParserException-&gt;InternalErrorOccurred</ns0:title>
<ns0:path fill="none" stroke="black" stroke-width="0.5" d="M158.72,-749031.8C168.42,-749031.8 178.4,-749031.8 188.27,-749031.8" />
<ns0:polygon fill="black" stroke="black" stroke-width="0.5" points="189.07,-749033.55 194.07,-749031.8 189.07,-749030.05 189.07,-749033.55" />
</ns0:g>
</ns0:g>
</ns0:svg>